import React from "react";
import PropTypes from "prop-types";
import { titleSortRestaurants } from "../../storage/reataurants";
import "./Filter.css";

// Renders set of controls to perform the text search and to choose the sorting
// method for the list of restaurants.
// Can be used multiply number on the same page, in the Top and Bottom, etc.
// Some CSS styles are set in "./List.css" file.
const filter = props => {
  const { searchText, sortKind, onSearchChange, onSortChange } = props;

  const renderDebug = () => {
    if (!props.isDebug) return null;

    // Todo: Move "Show Debug Info" outside the filter. Think about Header of Footer.
    const { isDebug, onDebugChange } = props;
    return (
      <label className="debug">
        <input type="checkbox" checked={isDebug} onChange={onDebugChange} />
        Show Debug Info
      </label>
    );
  };

  // Todo: make <option> tags automatically generated by sortKindRestaurants.forEach(...)
  return (
    <div className="filter">
      <label className="search">
        Search
        <input type="text" value={searchText} onChange={onSearchChange} />
      </label>

      {renderDebug()}

      <label className="sort">
        Sort
        <select value={sortKind} onChange={onSortChange}>
          <option value="0">{titleSortRestaurants.get(0)}</option>
          <option value="1">{titleSortRestaurants.get(1)}</option>
          <option value="2">{titleSortRestaurants.get(2)}</option>
          <option value="3">{titleSortRestaurants.get(3)}</option>
          <option value="4">{titleSortRestaurants.get(4)}</option>
          <option value="5">{titleSortRestaurants.get(5)}</option>
          <option value="6">{titleSortRestaurants.get(6)}</option>
          <option value="7">{titleSortRestaurants.get(7)}</option>
          <option value="8">{titleSortRestaurants.get(8)}</option>
          <option value="9">{titleSortRestaurants.get(9)}</option>
        </select>
      </label>
    </div>
  );
};

filter.propTypes = {
  searchText: PropTypes.string,
  sortKind: PropTypes.number,
  onSearchChange: PropTypes.func,
  onSortChange: PropTypes.func,
  isDebug: PropTypes.bool
};

export default filter;
